### ISSUE TITLE
Is Brainmorph expected to be better than Keymorph?

### ISSUE THREAD

**Issue by Fjr9516** [alanqrwang/keymorph#16]
Hi again,

Thank you very much for publishing this wonderful work!

I am trying to compare your methods and am struggling to determine the best-performing variant model between KeyMorph and BrainMorph. After reading your MedIA paper and BrainMorph arXiv paper, BrainMorph might be expected to perform better since it is trained on full resolution and with a larger model, whereas KeyMorph is trained on half resolution. However, I didn't see a direct comparison in the papers. So, a quick question should be: Is BrainMorph expected to be better than Keymorph?

**Comment by alanqrwang** [comment]
I would say KeyMorph and BrainMorph are not comparable in the way that you're describing. KeyMorph is a framework for training registration models, so it can be applied to any data that you want to register. In our MedIA paper, we used half-resolution brain data to verify that the framework works as proposed. 

On the other hand, BrainMorph is specifically for brain MRIs and uses the KeyMorph framework. Like you said, it is trained on full resolution with larger models, and thus it is intended for real world use cases where you want to register full resolution brain MRIs. If you're use case fits these criteria, then BrainMorph is the better solution. Otherwise, I would recommend using KeyMorph to train your own model on your own data.

Hope this helps.

**Comment by Fjr9516** [comment]
Thank you!
