### ISSUE TITLE
register.py not running

### ISSUE THREAD

**Issue by frheault** [alanqrwang/keymorph#6]
Maybe there is a versioning issue here? `ConvNetFC` is in `keymorph.net` and the module `keymorph.step` does not exist.

In register.py import list:
```
from keymorph.model import ConvNetFC, ConvNetCoM
from keymorph.step import step
```

**Comment by BBillot** [comment]
Hi and thanks for making your code publicly available.
I also have the same issue, I could locate ConvNetFC and ConvNetCoM in keymoprh.net but keymorph.step doesn't exist.
Also, I was wondering about input images having to be at 128^3 size. Is it a hard requirement, or can I still process images at 160^3 ?
Thanks
Benjamin

**Comment by BBillot** [comment]
Thanks a lot for fixing the issue !
However, I spotted another issue in pretraining in `from keymorph import loader_maker as loader` because loader_maker doesn't exist. This is important for me because I will need to retrain KeyMorph for fetal brain affine registration, and thus I need to do the pretraining first.

I was asking about 160 vs 128, because I also want to test on adult brains (where I can just take the trained KeyMorph), but based on your answer,  I might need to downsample images to fit the 128^3 requirements. Is that something that you had to do ? I didn't see anything like this in the paper, but maybe I missed something ?

Oh and one last question; if I want to compare against DLIR, I can just do so by changing the netowrk to ConvNetFC right ?

Thanks a lot in advance for your answers, and it's really appreciated that you make your code available with many explanations (which is always the case with Mert's and Adrian's students :+1: ).

**Comment by BBillot** [comment]
Actually, it looks like there are several problems with the pretraining script:
- there is no loader (loader_maker doesn't exist)
- no model is saved
- aug.affine_matrix doesn't exist

**Comment by alanqrwang** [comment]
Apologies, that script needed updating. I updated the script and the README for that section in this commit: https://github.com/alanqrwang/keymorph/commit/e7d8b7e019cca6ee74b7d974f7693a7c2e659027

**Comment by alanqrwang** [comment]
Closing now since there hasn't been follow up. Please do raise another issue if there's any further issues.
